INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, '.NET','Microsoft .NET');
INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, 'JAVA','ORACLE JAVA');
INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, 'NATURAL','NATURAL ADABAS');
INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, 'PHP','PHP');
INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, 'PORTALES','PORTALES');
INSERT  INTO TB_TECNOLOGIA (X_TECNOLOGIA,T_COD_TECNOLOGIA,T_DESCRIPCION) VALUES (SEQ_TECNOLOGIA.NEXTVAL, 'ARQUITECTURA','ARQUITECTURA');



INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Función Pública');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Servicios y Atención Ciudadana');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'Servicio de Sanidad Animal');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'Servicio Cántabro de Empleo');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. de Tesorería Presupuestos y Politica Financiera');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'S.G. Presidencia');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Desarrollo Rural');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. de Biodiversidad');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. de Servicios Sociales');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'C.E.A.R.C.');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Vivienda y Arquitectura');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'Intervención general');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Trabajo');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Hacienda');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'A.C.A.T.');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. de Pesca y Alimentación');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Tesorería');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Economía');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'D.G. Industria');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'Sanidad (DGOAS)');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'DGSP (Salud Pública)');
INSERT INTO TB_AREA_FUNCIONAL (X_AREA_FUNCIONAL, T_AREA_FUNCIONAL) VALUES (SEQ_AREA_FUNCIONAL.NEXTVAL, 'S.G. Obras Públicas');
