ALTER TABLE CONTROLSUMA.TB_ROL
ADD (	"T_DESCRIPCION" VARCHAR2(200 BYTE));
	
COMMENT ON COLUMN "TB_ROL"."T_DESCRIPCION" IS 'Descripcion del ROL';





ALTER TABLE CONTROLSUMA.TB_INVENTARIO_OTRAS
ADD (	
"T_DETALLE_INCIDENCIA"  VARCHAR2(200 BYTE),
"T_TIPO_INCIDENCIA" VARCHAR2(30 BYTE),
"T_DETALLE_GARANTIA"  VARCHAR2(200 BYTE),
"F_ULT_ACT_ANALISIS_FUNC" DATE,
"T_VALORACION_ANALISIS_FUNC" VARCHAR2(200 BYTE),
"T_DETALLE_ANALISIS_FUNC"  VARCHAR2(200 BYTE),
"T_DETALLE_INTEGRACION"  VARCHAR2(200 BYTE),
"T_TIPO_INTEGRACION" VARCHAR2(30 BYTE),
"T_VALORACION_MANUAL_INSTAL" VARCHAR2(200 BYTE),
"F_ULT_ACT_MANUAL_INSTAL" DATE,
"T_DETALLE_MANUAL_INSTAL"  VARCHAR2(200 BYTE),
"T_VALORACION_PLAN_PRUEBA" VARCHAR2(200 BYTE),
"T_DETALLE_PLAN_PRUEBA"  VARCHAR2(200 BYTE),
"F_ULT_ACT_PLAN_PRUEBA" DATE,
"T_DETALLE_DISENO"  VARCHAR2(200 BYTE),
"F_ULT_ACT_DISENO" DATE,
"T_VALORACION_DISENO" VARCHAR2(200 BYTE),
"L_GARANTIA" NUMBER(1,0),
"L_REQUIERE_SW" NUMBER(1,0),
"T_DOCU_CODIGO" VARCHAR2(200 BYTE)

);
	
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_INCIDENCIA" IS 'Descripcion de LA INCIDENCIA';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_TIPO_INCIDENCIA" IS 'Tipo de Incidencia';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_GARANTIA" IS 'Detalle garantia';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."F_ULT_ACT_ANALISIS_FUNC" IS 'Ultima actualizacion de analisis funcional';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_VALORACION_ANALISIS_FUNC" IS 'Valoracion del analisis funcional';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_ANALISIS_FUNC" IS 'Detalle analisis funcional';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_INTEGRACION" IS 'Detalle de integracion';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_TIPO_INTEGRACION" IS 'Tipo de integracion';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_VALORACION_MANUAL_INSTAL" IS 'Valoracion manual de instalacion';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."F_ULT_ACT_MANUAL_INSTAL" IS 'Ultima actualizacion del manual de instalacion';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_MANUAL_INSTAL" IS 'Detalle del manual de instalacion';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_VALORACION_PLAN_PRUEBA" IS 'Valoracion del plan de prueba';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_PLAN_PRUEBA" IS 'Detalle de plan de prueba';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DETALLE_DISENO" IS 'Detalle del diseño';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."F_ULT_ACT_DISENO" IS 'Ultima actualizacion del diseño';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_VALORACION_DISENO" IS 'Valoracion del diseño';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."L_GARANTIA" IS 'Existencia de garantia SI/NO';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."L_REQUIERE_SW" IS 'Requiere Software SI/NO';
COMMENT ON COLUMN "TB_INVENTARIO_OTRAS"."T_DOCU_CODIGO" IS 'Documentacion del codigo';



ALTER TABLE CONTROLSUMA.TB_ROL
ADD (	"N_CODJIRA" NUMBER(8,0));
	
COMMENT ON COLUMN "TB_ROL"."N_CODJIRA" IS 'CódigoJIRA';


ALTER TABLE CONTROLSUMA.TR_INVENTARIO_PERSONA
ADD ("ROL_X_ROL" NUMBER(8,0));

COMMENT ON COLUMN "TR_INVENTARIO_PERSONA"."ROL_X_ROL" IS 'Tipo de Responsable (G:Gobierno,S:Suma,U:Usuario Final,Desarrollador) ';

